apiVersion: v1
kind: Service
metadata:
  name: portable-openmldb-service
spec:
  selector:
    app: portable-openmldb
  ports:
  - name: zk
    port: 2181
    targetPort: 2181
    nodePort: 2181
  - name: nameserver
    port: 7527
    targetPort: 7527
    nodePort: 7527
  - name: tablet1
    port: 10921
    targetPort: 10921
    nodePort: 10921
  - name: tablet2
    port: 10922
    targetPort: 10922
    nodePort: 10922
  - name: apiserver
    port: 9080
    targetPort: 9080
    nodePort: 9080
  - name: taskmanager
    port: 9902
    targetPort: 9902
    nodePort: 9902
  type: NodePort
